name: Publish Package

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: 14

      - run: npm ci

      - run: npm test

      - run: npm run lint

  publish-npm:
    if: github.ref == 'refs/heads/master'

    needs: build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta

        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/

      - run: npm ci

      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-gpr:
    if: github.ref == 'refs/heads/master'

    needs: build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
          scope: '@firstclasspostcodes'

      - run: npm ci

      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
