name: "Build, test and release"

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 14
      - run: npm ci
      - run: npm run lint
      - run: npm test
      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v2
        with:
          branch: master
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Configure GPR
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
          scope: '@firstclasspostcodes'
      - name: Publish to GPR
        if: steps.semantic.outputs.new_release_published == 'true'
        run: npm publish --access public